// packages/solid/src/Map.tsx
import type { JSX, ParentProps } from 'solid-js'
import type { TsMap as TsMapInstance } from 'ts-maps'
import { createSignal, onCleanup, onMount } from 'solid-js'
import { TsMap } from 'ts-maps'
import { MapContext } from './context'

export interface MapProps {
  center?: [number, number]
  zoom?: number
  bearing?: number
  pitch?: number
  style?: JSX.CSSProperties
  class?: string
}

export function Map(props: ParentProps<MapProps>): JSX.Element {
  const [map, setMap] = createSignal<TsMapInstance | null>(null)
  let container: HTMLDivElement | undefined

  onMount(() => {
    if (!container)
      return
    const options: Record<string, unknown> = {}
    if (props.center !== undefined) options.center = props.center
    if (props.zoom !== undefined) options.zoom = props.zoom
    if (props.bearing !== undefined) options.bearing = props.bearing
    if (props.pitch !== undefined) options.pitch = props.pitch
    const instance = new TsMap(container, options)
    setMap(instance)
  })

  onCleanup(() => {
    const instance = map()
    try {
      ;(instance as unknown as { remove?: () => void } | null)?.remove?.()
    }
    catch {
      // ignore — host is being torn down
    }
    setMap(null)
  })

  return (
    <MapContext.Provider value={map}>
      <div ref={container} class={props.class} style={props.style}>
        {map() ? props.children : null}
      </div>
    </MapContext.Provider>
  )
}

// packages/svelte/src/Map.svelte
<script lang="ts">
  import { onDestroy, onMount, setContext } from 'svelte'
  import { TsMap } from 'ts-maps'
  import { MAP_CONTEXT_KEY, type MapContextValue } from './context'

  export let center: [number, number] | undefined = undefined
  export let zoom: number | undefined = undefined
  export let bearing: number | undefined = undefined
  export let pitch: number | undefined = undefined

  let container: HTMLDivElement | null = null
  let map: TsMap | null = null

  setContext<MapContextValue>(MAP_CONTEXT_KEY, { getMap: () => map })

  onMount(() => {
    if (!container) return
    const options: Record<string, unknown> = {}
    if (center !== undefined) options.center = center
    if (zoom !== undefined) options.zoom = zoom
    if (bearing !== undefined) options.bearing = bearing
    if (pitch !== undefined) options.pitch = pitch
    map = new TsMap(container, options)
  })

  onDestroy(() => {
    try {
      ;(map as unknown as { remove?: () => void } | null)?.remove?.()
    }
    catch {
      // ignore — host is being torn down
    }
    map = null
  })
</script>

<div bind:this={container} class="ts-map" style="width:100%;height:100%">
  {#if map}
    <slot />
  {/if}
</div>
