// packages/react/src/OfflineMaps.tsx
import type { OfflineMapsControlOptions, OfflineMaps as TsOfflineMapsManager } from 'ts-maps'
import type { ControlPosition } from './controls'
import { useEffect, useRef } from 'react'
import { OFFLINE_MAPS_EVENTS, OfflineMapsControl } from 'ts-maps'
import { useMap } from './useMap'

/* eslint-disable no-unused-vars */
export interface OfflineMapsEventProps {
  /** The list of downloaded maps changed: `{ regions }`. */
  onChange?: (e: any) => void
  /** A download moved on: `{ region }`. */
  onProgress?: (e: any) => void
  /** A download finished: `{ region }`. */
  onComplete?: (e: any) => void
  /** A download failed: `{ region, error }`. */
  onError?: (e: any) => void
  /** A downloaded map was deleted: `{ id }`. */
  onDelete?: (e: any) => void
  /** "Only Use Offline Maps" was switched: `{ onlyOffline }`. */
  onModeChange?: (e: any) => void
  /** The panel opened or closed: `{ open }`. */
  onOpenChange?: (e: any) => void
}
/* eslint-enable no-unused-vars */

export interface OfflineMapsProps extends OfflineMapsEventProps {
  /** Show the panel — the list of downloaded maps. */
  open?: boolean
  /** Never go to the network for map data. */
  onlyOffline?: boolean
  position?: ControlPosition
  /** The manager to show. Default: the page's, `offlineMaps()`. */
  maps?: TsOfflineMapsManager
  /** Names a new area by reverse geocoding its centre. */
  geocoder?: OfflineMapsControlOptions['geocoder']
  /** Other URLs to keep with every download, such as a TileJSON. */
  resources?: string[]
  /** The pill shown when the connection drops. Default true. */
  showStatus?: boolean
  title?: string
  /** The language its words are in. Default the map's `locale`, else the browser's. */
  locale?: string
  /** The underlying control; `control.maps` is the manager, for `download`, `list` and the rest. */
  // eslint-disable-next-line no-unused-vars
  onReady?: (control: OfflineMapsControl) => void
}

/**
 * Offline maps, after Apple Maps: a button opening the list of downloaded
 * maps, an area picker with an estimated size, and a pill when the
 * connection drops.
 *
 * ```tsx
 * <Map center={[37.78, -122.42]} zoom={13}>
 *   <OfflineMaps onComplete={({ region }) => toast(`${region.name} is ready offline`)} />
 * </Map>
 * ```
 *
 * Every prop is followed as it changes: a new `maps` moves the panel and its
 * events onto that manager, a new `position` moves the button.
 */
export function OfflineMaps(props: OfflineMapsProps): null {
  const map = useMap()
  const controlRef = useRef<OfflineMapsControl | null>(null)
  const latest = useRef(props)
  latest.current = props

  useEffect(() => {
    const { position, maps, geocoder, resources, showStatus, title, locale } = latest.current
    const offline = new OfflineMapsControl({ position, maps, geocoder, resources, showStatus, title, locale })
    offline.addTo(map)
    const stop = offline.listen((type, e) => (latest.current as any)[OFFLINE_MAPS_EVENTS[type]]?.(e))
    controlRef.current = offline
    latest.current.onReady?.(offline)
    return () => {
      stop()
      offline.remove()
      controlRef.current = null
    }
  }, [map])

  // Every option is followed; the control does nothing for one that has not
  // changed. Arrays are compared by value, so an inline `resources={[…]}`
  // is not a change on every render.
  const { open, onlyOffline, position, maps, geocoder, resources, showStatus, title, locale } = props
  const resourcesKey = JSON.stringify(resources ?? null)
  useEffect(() => {
    controlRef.current?.sync({ open, onlyOffline, position, maps, geocoder, resources, showStatus, title, locale })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map, open, onlyOffline, position, maps, geocoder, resourcesKey, showStatus, title, locale])

  return null
}

// packages/svelte/src/OfflineMaps.svelte
<script lang="ts">
  /**
   * Offline maps, after Apple Maps: a button opening the list of downloaded
   * maps, an area picker with an estimated size, and a pill when the
   * connection drops.
   *
   * ```svelte
   * <Map center={[37.78, -122.42]} zoom={13}>
   *   <OfflineMaps bind:open onComplete={({ region }) => toast(region.name)} />
   * </Map>
   * ```
   *
   * Every prop is followed as it changes: a new `maps` moves the panel and
   * its events onto that manager, a new `position` moves the button. `open`
   * and `onlyOffline` can be bound. Events are callback props with the same
   * names the other bindings use — `onChange`, `onProgress`, `onComplete`, …
   */
  import type { OfflineMapsControlOptions, OfflineMaps as TsOfflineMapsManager } from 'ts-maps'
  import { onDestroy, onMount } from 'svelte'
  import { OFFLINE_MAPS_EVENTS, OfflineMapsControl } from 'ts-maps'
  import { useMap } from './useMap'

  export let open: boolean | undefined = undefined
  export let onlyOffline: boolean | undefined = undefined
  export let position: 'topleft' | 'topright' | 'bottomleft' | 'bottomright' | undefined = undefined
  export let maps: TsOfflineMapsManager | undefined = undefined
  export let geocoder: OfflineMapsControlOptions['geocoder'] = undefined
  export let resources: string[] | undefined = undefined
  export let showStatus: boolean | undefined = undefined
  export let title: string | undefined = undefined
  /** The language its words are in. Default the map's `locale`, else the browser's. */
  export let locale: string | undefined = undefined

  /* eslint-disable no-unused-vars */
  export let onReady: ((control: OfflineMapsControl) => void) | undefined = undefined
  export let onChange: ((e: any) => void) | undefined = undefined
  export let onProgress: ((e: any) => void) | undefined = undefined
  export let onComplete: ((e: any) => void) | undefined = undefined
  export let onError: ((e: any) => void) | undefined = undefined
  export let onDelete: ((e: any) => void) | undefined = undefined
  export let onModeChange: ((e: any) => void) | undefined = undefined
  export let onOpenChange: ((e: any) => void) | undefined = undefined
  /* eslint-enable no-unused-vars */

  let offline: OfflineMapsControl | null = null
  let unlisten: (() => void) | null = null

  // Read at the moment of the event, so a changed handler is honoured.
  const handler = (prop: string): ((e: any) => void) | undefined => ({
    onChange, onProgress, onComplete, onError, onDelete, onModeChange, onOpenChange,
  } as Record<string, ((e: any) => void) | undefined>)[prop]

  onMount(() => {
    const map = useMap()
    if (!map) return
    offline = new OfflineMapsControl({ position, maps, geocoder, resources, showStatus, title, locale })
    offline.addTo(map)
    unlisten = offline.listen((type, e) => {
      // Kept in step, so `bind:open` and `bind:onlyOffline` see the panel's
      // own ✕ and switch.
      if (type === 'openchange') open = e.open
      else if (type === 'modechange') onlyOffline = e.onlyOffline
      handler(OFFLINE_MAPS_EVENTS[type])?.(e)
    })
    onReady?.(offline)
  })

  // Every option is followed; the control does nothing for one that has not
  // changed.
  $: if (offline) offline.sync({ open, onlyOffline, position, maps, geocoder, resources, showStatus, title, locale })

  onDestroy(() => {
    unlisten?.()
    offline?.remove()
    offline = null
  })
</script>
