// packages/solid/src/Search.tsx
import type { JSX } from 'solid-js'
import type { SearchControlOptions } from 'ts-maps'
import type { ControlPosition } from './controls'
import { createEffect, createSignal, onCleanup, untrack } from 'solid-js'
import { SEARCH_EVENTS, SearchControl } from 'ts-maps'
import { useMap } from './context'

/* eslint-disable no-unused-vars */
export interface SearchProps {
  /** Search for this; a category's name runs the category. Empty clears. */
  query?: string
  position?: ControlPosition
  placeholder?: string
  /** Online geocoder. Default Photon; `null` to search only the map and offline maps. */
  provider?: SearchControlOptions['provider']
  /** Downloaded maps to search. Default the page's; `null` for none. */
  offline?: SearchControlOptions['offline']
  categories?: SearchControlOptions['categories']
  recents?: boolean
  units?: SearchControlOptions['units']
  location?: SearchControlOptions['location']
  /** A `TurnByTurn` for Directions to preview routes on. */
  turnByTurn?: SearchControlOptions['turnByTurn']
  origin?: SearchControlOptions['origin']
  /** A `LookAround` — from `<LookAround onReady>` — for the place card's picture of the street. */
  lookAround?: SearchControlOptions['lookAround']
  language?: string
  /** The language its words are in. Default `language`, else the map's `locale`, else the browser's. */
  locale?: string
  /** Where a chosen place's hours, phone and website come from. Default OpenStreetMap; `null` for none. */
  details?: SearchControlOptions['details']
  /** The link Share sends. Default the place on openstreetmap.org. */
  shareUrl?: SearchControlOptions['shareUrl']
  /** Where Save keeps Favorites and Guides. Default the page's `savedPlaces()`; `null` for none. */
  saved?: SearchControlOptions['saved']
  /** Favorites as stars on the map. Default true. */
  showSaved?: boolean
  /** The underlying control, for `search`, `searchCategory`, `select` and `cancel`. */
  onReady?: (control: SearchControl) => void
  onResults?: (e: any) => void
  onSelect?: (e: any) => void
  /** A chosen place's hours, phone and website arrived: `{ place, details }`. */
  onDetails?: (e: any) => void
  /** Save on a place's card added it to Favorites: `{ place }`. */
  onSave?: (e: any) => void
  /** Save on a place's card took it out of Favorites: `{ place }`. */
  onUnsave?: (e: any) => void
  onDirections?: (e: any) => void
  onClear?: (e: any) => void
}
/* eslint-enable no-unused-vars */

/**
 * Search, after Apple Maps: "Search Maps" with Find Nearby and Recents,
 * suggestions as you type, pins for results, and a card with Directions.
 *
 * ```tsx
 * <Map center={[37.79, -122.41]} zoom={15}>
 *   <Search query={query()} onSelect={({ place }) => setChosen(place)} />
 * </Map>
 * ```
 *
 * Every prop is followed as it changes: a new `provider` is asked from the
 * next query on, new `categories` redraw Find Nearby in place.
 */
export function Search(props: SearchProps): JSX.Element {
  let search: SearchControl | null = null
  let unlisten: (() => void) | null = null
  const [control, setControl] = createSignal<SearchControl | null>(null)

  // An effect rather than onMount: the map arrives through a signal. The
  // options are read untracked here; the effects below follow them.
  createEffect(() => {
    const map = useMap()
    if (!map || search)
      return
    search = untrack(() => new SearchControl({
      position: props.position,
      placeholder: props.placeholder,
      provider: props.provider,
      offline: props.offline,
      categories: props.categories,
      recents: props.recents,
      units: props.units,
      location: props.location,
      turnByTurn: props.turnByTurn,
      origin: props.origin,
      lookAround: props.lookAround,
      language: props.language,
      locale: props.locale,
      details: props.details,
      shareUrl: props.shareUrl,
      saved: props.saved,
      showSaved: props.showSaved,
    }))
    search.addTo(map)
    unlisten = search.listen((type, e) => (props as any)[SEARCH_EVENTS[type]]?.(e))
    props.onReady?.(search)
    setControl(search)
  })

  // Every option is followed; the control does nothing for one that has not
  // changed. A `TurnByTurn` usually arrives after mount, from its own onReady,
  // and a `LookAround` the same way.
  createEffect(() => {
    const target = {
      position: props.position,
      placeholder: props.placeholder,
      provider: props.provider,
      offline: props.offline,
      categories: props.categories,
      recents: props.recents,
      units: props.units,
      location: props.location,
      turnByTurn: props.turnByTurn,
      origin: props.origin,
      lookAround: props.lookAround,
      language: props.language,
      locale: props.locale,
      details: props.details,
      shareUrl: props.shareUrl,
      saved: props.saved,
      showSaved: props.showSaved,
    }
    control()?.sync(target)
  })

  // `query` on its own, so another prop changing does not search again.
  createEffect(() => {
    const target = { query: props.query }
    control()?.sync(target)
  })

  onCleanup(() => {
    unlisten?.()
    search?.remove()
    search = null
  })

  return null as unknown as JSX.Element
}

// packages/svelte/src/Search.svelte
<script lang="ts">
  /**
   * Search, after Apple Maps: "Search Maps" with Find Nearby and Recents,
   * suggestions as you type, pins for results, and a card with Directions.
   *
   * ```svelte
   * <Map center={[37.79, -122.41]} zoom={15}>
   *   <Search {query} onSelect={({ place }) => (chosen = place)} />
   * </Map>
   * ```
   *
   * Every prop is followed as it changes: a new `provider` is asked from the
   * next query on, new `categories` redraw Find Nearby in place. Events are
   * callback props with the same names the other bindings use — `onResults`,
   * `onSelect`, `onDetails`, `onDirections`, `onSave`, `onUnsave`, `onClear`.
   * `saved` is where Save keeps Favorites (default the page's `savedPlaces()`,
   * `null` for none); `showSaved` puts them on the map as stars.
   */
  import type { SearchControlOptions } from 'ts-maps'
  import { onDestroy, onMount } from 'svelte'
  import { SEARCH_EVENTS, SearchControl } from 'ts-maps'
  import { useMap } from './useMap'

  export let query: string | undefined = undefined
  export let position: 'topleft' | 'topright' | 'bottomleft' | 'bottomright' | undefined = undefined
  export let placeholder: string | undefined = undefined
  export let provider: SearchControlOptions['provider'] = undefined
  export let offline: SearchControlOptions['offline'] = undefined
  export let categories: SearchControlOptions['categories'] = undefined
  export let recents: boolean | undefined = undefined
  export let units: SearchControlOptions['units'] = undefined
  export let location: SearchControlOptions['location'] = undefined
  export let turnByTurn: SearchControlOptions['turnByTurn'] = undefined
  export let origin: SearchControlOptions['origin'] = undefined
  /** A `LookAround` — from `<LookAround onReady>` — for the place card's picture of the street. */
  export let lookAround: SearchControlOptions['lookAround'] = undefined
  export let language: string | undefined = undefined
  /** The language its words are in. Default `language`, else the map's `locale`, else the browser's. */
  export let locale: string | undefined = undefined
  export let details: SearchControlOptions['details'] = undefined
  export let shareUrl: SearchControlOptions['shareUrl'] = undefined
  export let saved: SearchControlOptions['saved'] = undefined
  export let showSaved: boolean | undefined = undefined

  /* eslint-disable no-unused-vars */
  export let onReady: ((control: SearchControl) => void) | undefined = undefined
  export let onResults: ((e: any) => void) | undefined = undefined
  export let onSelect: ((e: any) => void) | undefined = undefined
  export let onDetails: ((e: any) => void) | undefined = undefined
  export let onDirections: ((e: any) => void) | undefined = undefined
  export let onSave: ((e: any) => void) | undefined = undefined
  export let onUnsave: ((e: any) => void) | undefined = undefined
  export let onClear: ((e: any) => void) | undefined = undefined
  /* eslint-enable no-unused-vars */

  let search: SearchControl | null = null
  let unlisten: (() => void) | null = null

  // Read at the moment of the event, so a changed handler is honoured.
  const handler = (prop: string): ((e: any) => void) | undefined => ({
    onResults, onSelect, onDetails, onDirections, onSave, onUnsave, onClear,
  } as Record<string, ((e: any) => void) | undefined>)[prop]

  onMount(() => {
    const map = useMap()
    if (!map) return
    search = new SearchControl({ position, placeholder, provider, offline, categories, recents, units, location, turnByTurn, origin, lookAround, language, locale, details, shareUrl, saved, showSaved })
    search.addTo(map)
    unlisten = search.listen((type, e) => handler(SEARCH_EVENTS[type])?.(e))
    onReady?.(search)
  })

  // Every option is followed; the control does nothing for one that has not
  // changed. A `TurnByTurn` usually arrives after mount, from its own
  // onReady, and a `LookAround` the same way. The query is followed on its
  // own, so another option does not search again.
  $: if (search) search.sync({ position, placeholder, provider, offline, categories, recents, units, location, turnByTurn, origin, lookAround, language, locale, details, shareUrl, saved, showSaved })
  $: if (search) search.sync({ query })

  onDestroy(() => {
    unlisten?.()
    search?.remove()
    search = null
  })
</script>
