// packages/solid/src/TurnByTurn.tsx
import type { JSX } from 'solid-js'
import type { LatLngInput, TurnByTurnOptions } from 'ts-maps'
import { createEffect, onCleanup } from 'solid-js'
import { TURN_BY_TURN_EVENTS, TurnByTurn as TsTurnByTurn } from 'ts-maps'
import { useMap } from './context'

/* eslint-disable no-unused-vars */
export interface TurnByTurnProps {
  /** Where the trip starts, `[lat, lng]` or `{ lat, lng }`. */
  from?: LatLngInput | null
  /** Where it ends. With both set, the routes between them are previewed. */
  to?: LatLngInput | null
  /** Guide along the chosen route. Off returns to the preview. */
  active?: boolean
  profile?: TurnByTurnOptions['profile']
  units?: TurnByTurnOptions['units']
  voice?: boolean
  simulate?: TurnByTurnOptions['simulate']
  alternatives?: boolean
  destinationName?: string
  directions?: TurnByTurnOptions['directions']
  /** The language of its cards and voice. Default the map's `locale`, else the browser's. */
  locale?: string
  /** The underlying `TurnByTurn`, for `selectRoute`, `recenter` and `update`. */
  onReady?: (nav: TsTurnByTurn) => void
  onPreview?: (e: any) => void
  onRouteSelect?: (e: any) => void
  onStart?: (e: any) => void
  onProgress?: (e: any) => void
  onInstruction?: (e: any) => void
  onReroute?: (e: any) => void
  onArrive?: (e: any) => void
  onEnd?: (e: any) => void
  onError?: (e: any) => void
}
/* eslint-enable no-unused-vars */

/**
 * Turn-by-turn navigation, after Apple Maps.
 *
 * ```tsx
 * <Map center={[37.79, -122.39]} zoom={13}>
 *   <TurnByTurn from={[37.7955, -122.3937]} to={[37.8029, -122.4484]} active={driving()} />
 * </Map>
 * ```
 *
 * Setting `from` and `to` previews the routes; `active` starts guidance.
 * Every prop is followed as it changes.
 */
export function TurnByTurn(props: TurnByTurnProps): JSX.Element {
  let nav: TsTurnByTurn | null = null

  // One effect for both: the map arrives through a signal, and every prop is
  // read here too, so a change to either brings the navigation into line —
  // whichever comes first. Another `profile` or `directions` fetches a
  // showing preview again; places are compared by value, so an unchanged
  // trip is not fetched again when another prop changes.
  createEffect(() => {
    const map = useMap()
    const target = {
      from: props.from,
      to: props.to,
      active: props.active,
      profile: props.profile,
      units: props.units,
      voice: props.voice,
      simulate: props.simulate,
      alternatives: props.alternatives,
      destinationName: props.destinationName,
      directions: props.directions,
      locale: props.locale,
    }
    if (!map)
      return
    if (!nav) {
      nav = new TsTurnByTurn(map, {
        profile: target.profile,
        units: target.units,
        voice: target.voice,
        simulate: target.simulate,
        alternatives: target.alternatives,
        destinationName: target.destinationName,
        directions: target.directions,
        locale: target.locale,
      })
      for (const [event, prop] of Object.entries(TURN_BY_TURN_EVENTS))
        nav.on(event, (e: any) => (props as any)[prop]?.(e))
      props.onReady?.(nav)
    }
    nav.sync(target)
  })

  onCleanup(() => {
    nav?.stop()
    nav = null
  })

  return null as unknown as JSX.Element
}

// packages/react/src/TurnByTurn.tsx
import type { LatLngInput, TurnByTurnOptions } from 'ts-maps'
import { useEffect, useRef } from 'react'
import { TURN_BY_TURN_EVENTS, TurnByTurn as TsTurnByTurn } from 'ts-maps'
import { useMap } from './useMap'

/* eslint-disable no-unused-vars */
export interface TurnByTurnEventProps {
  /** Routes are on the map and the card is showing. */
  onPreview?: (e: any) => void
  onRouteSelect?: (e: any) => void
  /** Guidance began. */
  onStart?: (e: any) => void
  /** Every position: distance and time left, the next maneuver, lanes. */
  onProgress?: (e: any) => void
  /** Something was said, or would have been with the voice off. */
  onInstruction?: (e: any) => void
  onReroute?: (e: any) => void
  onArrive?: (e: any) => void
  /** Guidance ended — End was tapped, or `active` went false. */
  onEnd?: (e: any) => void
  onError?: (e: any) => void
}
/* eslint-enable no-unused-vars */

export interface TurnByTurnProps extends TurnByTurnEventProps {
  /** Where the trip starts, `[lat, lng]` or `{ lat, lng }`. */
  from?: LatLngInput | null
  /** Where it ends. With both set, the routes between them are previewed. */
  to?: LatLngInput | null
  /** Guide along the chosen route. Off returns to the preview. */
  active?: boolean
  profile?: TurnByTurnOptions['profile']
  units?: TurnByTurnOptions['units']
  voice?: boolean
  simulate?: TurnByTurnOptions['simulate']
  alternatives?: boolean
  destinationName?: string
  directions?: TurnByTurnOptions['directions']
  /** The language of its cards and voice. Default the map's `locale`, else the browser's. */
  locale?: string
  /** The underlying `TurnByTurn`, for `selectRoute`, `recenter` and `update`. */
  // eslint-disable-next-line no-unused-vars
  onReady?: (nav: TsTurnByTurn) => void
}

/**
 * Turn-by-turn navigation, after Apple Maps.
 *
 * ```tsx
 * <Map center={[37.79, -122.39]} zoom={13}>
 *   <TurnByTurn from={[37.7955, -122.3937]} to={[37.8029, -122.4484]} active={driving} onArrive={done} />
 * </Map>
 * ```
 *
 * Setting `from` and `to` previews the routes; `active` starts guidance.
 * Every prop is followed as it changes.
 */
export function TurnByTurn(props: TurnByTurnProps): null {
  const map = useMap()
  const navRef = useRef<TsTurnByTurn | null>(null)
  // The latest handlers, so a re-render with new callbacks is honoured
  // without re-subscribing.
  const latest = useRef(props)
  latest.current = props

  useEffect(() => {
    const { profile, units, voice, simulate, alternatives, destinationName, directions, locale } = latest.current
    const nav = new TsTurnByTurn(map, { profile, units, voice, simulate, alternatives, destinationName, directions, locale })
    for (const [event, prop] of Object.entries(TURN_BY_TURN_EVENTS))
      nav.on(event, (e: any) => (latest.current as any)[prop]?.(e))
    navRef.current = nav
    latest.current.onReady?.(nav)
    return () => {
      nav.stop()
      navRef.current = null
    }
  }, [map])

  // Every option is followed: another `profile` or `directions` fetches a
  // showing preview again, `units` redraw the cards in place. Places and
  // `simulate` are compared by value, so inline literals are not a change.
  const { from, to, active, profile, units, voice, simulate, alternatives, destinationName, directions, locale } = props
  const fromKey = JSON.stringify(from ?? null)
  const toKey = JSON.stringify(to ?? null)
  const simulateKey = JSON.stringify(simulate ?? null)
  useEffect(() => {
    navRef.current?.sync({ from, to, active, profile, units, voice, simulate, alternatives, destinationName, directions, locale })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map, fromKey, toKey, active, profile, units, voice, simulateKey, alternatives, destinationName, directions, locale])

  return null
}
