// packages/nuxt/src/runtime/components/VectorMap.vue
<script setup lang="ts">
import type { MapData, MapOptions } from 'ts-maps'
import type { ComputedRef, PropType, Ref } from 'vue'
import { VectorMap as TsVectorMap } from 'ts-maps'
import brasilMap from 'ts-maps/brasil'
import canadaMap from 'ts-maps/canada'
import italyMap from 'ts-maps/italy'
import russiaMap from 'ts-maps/russia'
import spainMap from 'ts-maps/spain'
import usaAeaMap from 'ts-maps/us-aea-en'
import usaLccMap from 'ts-maps/us-lcc-en'
import usaMercMap from 'ts-maps/us-merc-en'
import usaMillMap from 'ts-maps/us-mill-en'
import worldMap from 'ts-maps/world'
import worldMercMap from 'ts-maps/world-merc'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'

// Map name type
type MapName = 'world'
  | 'world-merc'
  | 'us-merc'
  | 'us-mill'
  | 'us-lcc'
  | 'us-aea'
  | 'spain'
  | 'italy'
  | 'canada'
  | 'brasil'
  | 'russia'

const props = defineProps({
  options: {
    type: Object as PropType<Omit<MapOptions, 'selector'>>,
    required: true,
  },
  mapName: {
    type: String as PropType<MapName>,
    required: true,
  },
  width: {
    type: String,
    default: '100%',
  },
  height: {
    type: String,
    default: '400px',
  },
})

const emit = defineEmits<{
  (e: 'regionClick', event: MouseEvent, code: string): void
  (e: 'regionSelected', event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]): void
  (e: 'markerClick', event: MouseEvent, index: string): void
  (e: 'viewportChange', scale: number, transX: number, transY: number): void
  (e: 'loaded'): void
  (e: 'update:options', options: MapOptions): void
}>()

const mapContainer: Ref<HTMLElement | null> = ref(null)
const map: Ref<TsVectorMap | null> = ref(null)
const loading: Ref<boolean> = ref(true)

const containerStyle: ComputedRef<{ width: string, height: string, position: 'relative' }> = computed(() => ({
  width: props.width,
  height: props.height,
  position: 'relative' as const,
}))

// Map data lookup
const mapData: Record<MapName, MapData> = {
  'world': worldMap as MapData,
  'world-merc': worldMercMap as MapData,
  'us-merc': usaMercMap as MapData,
  'us-mill': usaMillMap as MapData,
  'us-lcc': usaLccMap as MapData,
  'us-aea': usaAeaMap as MapData,
  'spain': spainMap as MapData,
  'italy': italyMap as MapData,
  'canada': canadaMap as MapData,
  'brasil': brasilMap as MapData,
  'russia': russiaMap as MapData,
}

onMounted(async () => {
  if (!mapContainer.value)
    return

  const containerId: string = mapContainer.value.id || `ts-maps-${Math.random().toString(36).substring(2, 11)}`
  mapContainer.value.id = containerId

  // Add the map data
  TsVectorMap.addMap(props.mapName, mapData[props.mapName])

  // Initialize the map with the selected map
  map.value = new TsVectorMap({
    ...props.options,
    map: {
      name: props.mapName,
      projection: props.options.projection,
    },
    selector: `#${containerId}`,
    onRegionClick: (event: MouseEvent, code: string) => {
      emit('regionClick', event, code)
    },
    onRegionSelected: (event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => {
      emit('regionSelected', event, code, isSelected, selectedRegions)
    },
    onMarkerClick: (event: MouseEvent, index: string) => {
      emit('markerClick', event, index)
    },
    onViewportChange: (scale: number, transX: number, transY: number) => {
      emit('viewportChange', scale, transX, transY)
    },
    onLoaded: () => {
      loading.value = false
      emit('loaded')
    },
  })
})

// Watch for options changes
watch(() => props.options, (newOptions) => {
  if (map.value) {
    Object.assign(map.value, newOptions)
    emit('update:options', {
      ...newOptions,
      selector: `#${mapContainer.value?.id}`,
      map: {
        name: props.mapName,
        projection: newOptions.projection,
      },
    })
  }
}, { deep: true })

// Watch for map name changes
watch(() => props.mapName, (newMapName) => {
  if (mapContainer.value && mapData[newMapName]) {
    // Add the new map data
    TsVectorMap.addMap(newMapName, mapData[newMapName])

    // Create a new map instance with the new map
    map.value = new TsVectorMap({
      ...props.options,
      map: {
        name: newMapName,
        projection: props.options.projection,
      },
      selector: `#${mapContainer.value.id}`,
      onRegionClick: (event: MouseEvent, code: string) => {
        emit('regionClick', event, code)
      },
      onRegionSelected: (event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => {
        emit('regionSelected', event, code, isSelected, selectedRegions)
      },
      onMarkerClick: (event: MouseEvent, index: string) => {
        emit('markerClick', event, index)
      },
      onViewportChange: (scale: number, transX: number, transY: number) => {
        emit('viewportChange', scale, transX, transY)
      },
      onLoaded: () => {
        loading.value = false
        emit('loaded')
      },
    })
  }
})

onBeforeUnmount(() => {
  if (map.value) {
    // Clean up the map instance
    map.value = null
  }
})

// Expose the map instance to the parent component
defineExpose({
  map,
})
</script>

<template>
  <div ref="mapContainer" :style="containerStyle">
    <slot v-if="loading" name="loading">
      <div class="ts-maps-loading">
        Loading map...
      </div>
    </slot>
  </div>
</template>

<style>
.ts-maps-loading {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  color: #666;
}
</style>

// packages/react/src/components/VectorMap.tsx
import type { MapOptions } from 'ts-maps'
import { useEffect, useRef, useState } from 'react'
import worldMap, { VectorMap as TSVectorMap } from 'ts-maps'

export interface VectorMapProps extends Omit<React.HTMLProps<HTMLDivElement>, 'ref'> {
  options: Omit<MapOptions, 'selector'>
  mapName: string
  width?: number | string
  height?: number | string
  onRegionClick?: (event: MouseEvent, code: string) => void
  onMarkerClick?: (event: MouseEvent, index: string) => void
  onLoaded?: () => void
  onViewportChange?: (x: number, y: number, z: number) => void
  onRegionSelected?: (event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => void
  onMarkerSelected?: (event: MouseEvent, index: string, isSelected: boolean, selectedMarkers: string[]) => void
  onRegionTooltipShow?: (event: Event, tooltip: any, code: string) => void
  onMarkerTooltipShow?: (event: Event, tooltip: any, index: string) => void
  children?: React.ReactNode
}

export function VectorMap({
  options,
  mapName,
  width = '100%',
  height = '400px',
  onRegionClick,
  onMarkerClick,
  onLoaded,
  onViewportChange,
  onRegionSelected,
  onMarkerSelected,
  onRegionTooltipShow,
  onMarkerTooltipShow,
  style,
  children,
  ...props
}: VectorMapProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<TSVectorMap | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!containerRef.current)
      return

    const containerId = containerRef.current.id || `ts-maps-${Math.random().toString(36).substring(2, 11)}`
    containerRef.current.id = containerId

    const map = new TSVectorMap({
      ...options,
      map: {
        name: mapName,
        ...options.map,
      },
      selector: `#${containerId}`,
      onRegionClick: (event: MouseEvent, code: string) => {
        onRegionClick?.(event, code)
      },
      onRegionSelected: (event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => {
        onRegionSelected?.(event, code, isSelected, selectedRegions)
      },
      onMarkerClick: (event: MouseEvent, index: string) => {
        onMarkerClick?.(event, index)
      },
      onMarkerSelected: (event: MouseEvent, index: string, isSelected: boolean, selectedMarkers: string[]) => {
        onMarkerSelected?.(event, index, isSelected, selectedMarkers)
      },
      onViewportChange: (x: number, y: number, z: number) => {
        onViewportChange?.(x, y, z)
      },
      onRegionTooltipShow: (event: Event, tooltip: any, code: string) => {
        onRegionTooltipShow?.(event, tooltip, code)
      },
      onMarkerTooltipShow: (event: Event, tooltip: any, index: string) => {
        onMarkerTooltipShow?.(event, tooltip, index)
      },
      onLoaded: () => {
        setLoading(false)
        onLoaded?.()
      },
    })

    mapRef.current = map

    return () => {
      if (mapRef.current) {
        mapRef.current = null
      }
    }
  }, [options, mapName, onRegionClick, onMarkerClick, onLoaded, onViewportChange, onRegionSelected, onMarkerSelected, onRegionTooltipShow, onMarkerTooltipShow])

  const containerStyle: React.CSSProperties = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    position: 'relative',
    ...style,
  }

  return (
    <div
      {...props}
      ref={containerRef}
      style={containerStyle}
    >
      {loading && (
        <div className="ts-maps-loading">
          {children || 'Loading map...'}
        </div>
      )}
    </div>
  )
}

// Add CSS styles for loading state
const styles = `
.ts-maps-loading {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  color: #666;
}
`

// Inject styles if not already present
if (typeof document !== 'undefined' && !document.getElementById('ts-maps-styles')) {
  const styleElement = document.createElement('style')
  styleElement.id = 'ts-maps-styles'
  styleElement.textContent = styles
  document.head.appendChild(styleElement)
}
