// packages/react/src/components/UnitedStates.tsx
import type { MapOptions } from 'ts-maps'
import { useEffect, useMemo, useRef } from 'react'
import { VectorMap as TSVectorMap } from 'ts-maps'
import usMap from 'ts-maps/us-aea-en'
import './map-components.css'

export interface UnitedStatesProps extends Omit<React.HTMLProps<HTMLDivElement>, 'ref'> {
  options: Omit<MapOptions, 'selector'>
  height?: string
  mapKey?: string | number // Optional key for forcing re-renders
  onRegionClick?: (event: MouseEvent, code: string) => void
  onMarkerClick?: (event: MouseEvent, index: string) => void
  onLoaded?: () => void
  onViewportChange?: (x: number, y: number, z: number) => void
  onRegionSelected?: (event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => void
  onMarkerSelected?: (event: MouseEvent, index: string, isSelected: boolean, selectedMarkers: string[]) => void
  onRegionTooltipShow?: (event: Event, tooltip: any, code: string) => void
  onMarkerTooltipShow?: (event: Event, tooltip: any, index: string) => void
}

export function UnitedStates({
  options,
  height = '500px',
  mapKey,
  onRegionClick,
  onMarkerClick,
  onLoaded,
  onViewportChange,
  onRegionSelected,
  onMarkerSelected,
  onRegionTooltipShow,
  onMarkerTooltipShow,
  style,
  ...props
}: UnitedStatesProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<TSVectorMap | null>(null)

  // Generate a key based on options to force re-render when options change significantly
  const computedMapKey = useMemo(() => {
    if (mapKey !== undefined)
      return mapKey

    const optionsHash = JSON.stringify({
      backgroundColor: options.backgroundColor,
      zoomOnScroll: options.zoomOnScroll,
      regionsSelectable: options.regionsSelectable,
      markersSelectable: options.markersSelectable,
      visualizeData: options.visualizeData,
      markers: options.markers?.length,
    })

    return `us-map-${optionsHash.length}-${Date.now()}`
  }, [mapKey, options])

  useEffect(() => {
    if (!containerRef.current)
      return

    // Add US map
    TSVectorMap.addMap('us-aea', usMap)

    const map = new TSVectorMap({
      selector: `#${containerRef.current.id}`,
      map: {
        name: 'us-aea',
        ...options.map,
      },
      ...options,
    })

    // Set up event listeners
    if (onRegionClick) {
      map.on('regionClick', onRegionClick)
    }
    if (onMarkerClick) {
      map.on('markerClick', onMarkerClick)
    }
    if (onLoaded) {
      map.on('loaded', onLoaded)
    }
    if (onViewportChange) {
      map.on('viewportChange', onViewportChange)
    }
    if (onRegionSelected) {
      map.on('regionSelected', onRegionSelected)
    }
    if (onMarkerSelected) {
      map.on('markerSelected', onMarkerSelected)
    }
    if (onRegionTooltipShow) {
      map.on('regionTooltipShow', onRegionTooltipShow)
    }
    if (onMarkerTooltipShow) {
      map.on('markerTooltipShow', onMarkerTooltipShow)
    }

    mapRef.current = map

    return () => {
      if (mapRef.current) {
        // Clean up event listeners
        if (onRegionClick) {
          mapRef.current.off('regionClick', onRegionClick)
        }
        if (onMarkerClick) {
          mapRef.current.off('markerClick', onMarkerClick)
        }
        if (onLoaded) {
          mapRef.current.off('loaded', onLoaded)
        }
        if (onViewportChange) {
          mapRef.current.off('viewportChange', onViewportChange)
        }
        if (onRegionSelected) {
          mapRef.current.off('regionSelected', onRegionSelected)
        }
        if (onMarkerSelected) {
          mapRef.current.off('markerSelected', onMarkerSelected)
        }
        if (onRegionTooltipShow) {
          mapRef.current.off('regionTooltipShow', onRegionTooltipShow)
        }
        if (onMarkerTooltipShow) {
          mapRef.current.off('markerTooltipShow', onMarkerTooltipShow)
        }

        mapRef.current = null
      }
    }
  }, [computedMapKey, options, onRegionClick, onMarkerClick, onLoaded, onViewportChange, onRegionSelected, onMarkerSelected, onRegionTooltipShow, onMarkerTooltipShow])

  const containerStyle: React.CSSProperties = {
    height,
    ...style,
  }

  return (
    <div
      {...props}
      ref={containerRef}
      id={`us-map-${Math.random().toString(36).slice(2, 11)}`}
      style={containerStyle}
    >
      <div className="us-map-loading">
        Loading United States map...
      </div>
    </div>
  )
}

// packages/nuxt/src/runtime/components/VectorMaps/UnitedStates.vue
<script setup lang="ts">
import type { MapOptions } from 'ts-maps'
import { computed } from 'vue'
import VectorMap from '../VectorMap.vue'

// Props interface
interface Props {
  options: Omit<MapOptions, 'selector'>
  height?: string
  mapKey?: string | number // Optional key for forcing re-renders
}

// Events interface
interface Emits {
  (e: 'regionClick', event: MouseEvent, code: string): void
  (e: 'markerClick', event: MouseEvent, index: string): void
  (e: 'loaded'): void
  (e: 'viewportChange', x: number, y: number, z: number): void
  (e: 'regionSelected', event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]): void
  (e: 'markerSelected', event: MouseEvent, index: string, isSelected: boolean, selectedMarkers: string[]): void
  (e: 'regionTooltipShow', event: Event, tooltip: any, code: string): void
  (e: 'markerTooltipShow', event: Event, tooltip: any, index: string): void
}

// Props with defaults
const props = withDefaults(defineProps<Props>(), {
  height: '500px',
  mapKey: undefined,
})

// Emit events
const emit = defineEmits<Emits>()

// Computed map key - use provided key or generate one based on options
const mapKey = computed(() => {
  if (props.mapKey !== undefined)
    return props.mapKey

  // Generate a key based on options to force re-render when options change significantly
  const optionsHash = JSON.stringify({
    backgroundColor: props.options.backgroundColor,
    zoomOnScroll: props.options.zoomOnScroll,
    regionsSelectable: props.options.regionsSelectable,
    markersSelectable: props.options.markersSelectable,
    visualizeData: props.options.visualizeData,
    markers: props.options.markers?.length,
  })

  return `us-map-${optionsHash.length}-${Date.now()}`
})
</script>

<template>
  <VectorMap
    :key="mapKey"
    :options="options"
    map-name="us-aea"
    :height="height"
    @region-click="(event: MouseEvent, code: string) => emit('regionClick', event, code)"
    @marker-click="(event: MouseEvent, index: string) => emit('markerClick', event, index)"
    @loaded="() => emit('loaded')"
    @viewport-change="(x: number, y: number, z: number) => emit('viewportChange', x, y, z)"
    @region-selected="(event: MouseEvent, code: string, isSelected: boolean, selectedRegions: string[]) => emit('regionSelected', event, code, isSelected, selectedRegions)"
    @marker-selected="(event: MouseEvent, index: string, isSelected: boolean, selectedMarkers: string[]) => emit('markerSelected', event, index, isSelected, selectedMarkers)"
    @region-tooltip-show="(event: Event, tooltip: any, code: string) => emit('regionTooltipShow', event, tooltip, code)"
    @marker-tooltip-show="(event: Event, tooltip: any, index: string) => emit('markerTooltipShow', event, tooltip, index)"
  >
    <template #loading>
      <slot name="loading">
        <div class="us-map-loading">
          Loading United States map...
        </div>
      </slot>
    </template>
  </VectorMap>
</template>

<style scoped>
.us-map-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  background: rgba(255, 255, 255, 0.9);
  font-size: 1.2em;
  color: #666;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
</style>
