// packages/react/src/controls.tsx
import type { ComponentType } from 'react'
import { useEffect, useRef } from 'react'
import { control } from 'ts-maps'
import { useMapOptional } from './useMap'

/**
 * Declarative wrappers for the map's controls.
 *
 * Controls were previously reachable only through `useMap()` and an effect,
 * which meant every app wrote the same add-on-mount / remove-on-unmount dance.
 * They are placed UI, so they belong in the tree with everything else:
 *
 * ```tsx
 * <Map center={[34.02, -118.47]} zoom={14}>
 *   <NavigationControl position="topright" showCompass />
 *   <GeocoderControl placeholder="Search for a place" />
 * </Map>
 * ```
 *
 * `LayersControl` is deliberately absent: it takes base-layer and overlay
 * dictionaries of live layer instances, which is imperative by nature. Reach
 * for `useMap()` and `control.layers(...)` for that one.
 */

export type ControlPosition = 'topleft' | 'topright' | 'bottomleft' | 'bottomright'

export interface ControlProps {
  position?: ControlPosition
  /** Anything else the underlying control accepts. */
  options?: Record<string, unknown>
}

type ControlFactory = (options?: any) => { addTo: (map: any) => unknown, remove: () => unknown }

/**
 * Build a component from a control factory.
 *
 * Options are read through a ref rather than listed in the dependency array so
 * an inline object literal — the normal way to write these props — does not
 * tear the control down and rebuild it on every render. Changing `position`
 * does rebuild, because that is what moving a control means, and so does
 * changing `locale`: a control writes its titles when it is built.
 */
function createControlComponent<P extends ControlProps>(
  factory: ControlFactory,
  displayName: string,
): ComponentType<P> {
  function Control(props: P): null {
    const map = useMapOptional()
    const propsRef = useRef(props)
    propsRef.current = props

    useEffect(() => {
      if (!map)
        return

      const { position, options, ...rest } = propsRef.current
      const instance = factory({
        ...(position ? { position } : {}),
        ...rest,
        ...options,
      })
      instance.addTo(map)

      return () => {
        instance.remove()
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [map, props.position, (props as { locale?: string }).locale])

    return null
  }

  Control.displayName = displayName
  return Control as ComponentType<P>
}

export interface ZoomControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  zoomInTitle?: string
  zoomOutTitle?: string
}

export interface NavigationControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  showZoom?: boolean
  showCompass?: boolean
  visualizePitch?: boolean
  resetDuration?: number
  compassTitle?: string
}

export interface GeocoderControlProps extends ControlProps {
  provider?: unknown
  placeholder?: string
  limit?: number
  debounce?: number
  minLength?: number
  collapsed?: boolean
  flyTo?: boolean
  zoom?: number
  marker?: boolean
  proximity?: boolean
  language?: string
  countries?: string[]
}

export interface FullscreenControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  container?: HTMLElement
  title?: string
  titleCancel?: string
}

export interface LocateControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  zoom?: number | null
  follow?: boolean
  showMarker?: boolean
  enableHighAccuracy?: boolean
  timeout?: number
  maximumAge?: number
}

export interface ScaleControlProps extends ControlProps {
  metric?: boolean
  imperial?: boolean
  maxWidth?: number
}

export interface AttributionControlProps extends ControlProps {
  prefix?: string | false
}

export const ZoomControl: ComponentType<ZoomControlProps>
  = createControlComponent<ZoomControlProps>(control.zoom as ControlFactory, 'ZoomControl')

export const NavigationControl: ComponentType<NavigationControlProps>
  = createControlComponent<NavigationControlProps>(control.navigation as ControlFactory, 'NavigationControl')

export const GeocoderControl: ComponentType<GeocoderControlProps>
  = createControlComponent<GeocoderControlProps>(control.geocoder as ControlFactory, 'GeocoderControl')

export const FullscreenControl: ComponentType<FullscreenControlProps>
  = createControlComponent<FullscreenControlProps>(control.fullscreen as ControlFactory, 'FullscreenControl')

export const LocateControl: ComponentType<LocateControlProps>
  = createControlComponent<LocateControlProps>(control.locate as ControlFactory, 'LocateControl')

export const ScaleControl: ComponentType<ScaleControlProps>
  = createControlComponent<ScaleControlProps>(control.scale as ControlFactory, 'ScaleControl')

export const AttributionControl: ComponentType<AttributionControlProps>
  = createControlComponent<AttributionControlProps>(control.attribution as ControlFactory, 'AttributionControl')

// packages/solid/src/controls.tsx
import type { JSX } from 'solid-js'
import { createEffect, onCleanup } from 'solid-js'
import { control } from 'ts-maps'
import { useMap } from './context'

/**
 * Declarative wrappers for the map's controls.
 *
 * ```tsx
 * <Map center={[34.02, -118.47]} zoom={14}>
 *   <NavigationControl position="topright" showCompass />
 *   <GeocoderControl placeholder="Search for a place" />
 * </Map>
 * ```
 *
 * `LayersControl` is deliberately absent: it takes dictionaries of live layer
 * instances, which is imperative by nature. Use `useMap()` and
 * `control.layers(...)` for that one.
 */

export type ControlPosition = 'topleft' | 'topright' | 'bottomleft' | 'bottomright'

export interface ControlProps {
  position?: ControlPosition
  /** Anything else the underlying control accepts. */
  options?: Record<string, unknown>
}

type ControlFactory = (options?: any) => { addTo: (map: any) => unknown, remove: () => unknown }

function createControlComponent<P extends ControlProps>(factory: ControlFactory) {
  return function Control(props: P): JSX.Element {
    let instance: ReturnType<ControlFactory> | null = null

    // An effect rather than onMount: the map arrives through a signal, so a
    // control mounted in the same tick as the map would otherwise find nothing
    // to attach to. Every prop is read here, so a new one, `locale` among
    // them, makes the control again.
    createEffect(() => {
      const map = useMap()
      if (!map)
        return

      const { position, options, ...rest } = props
      instance?.remove()
      instance = factory({
        ...(position ? { position } : {}),
        ...rest,
        ...options,
      })
      instance.addTo(map)
    })

    onCleanup(() => {
      instance?.remove()
      instance = null
    })

    return null
  }
}

export interface ZoomControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  zoomInTitle?: string
  zoomOutTitle?: string
}

export interface NavigationControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  showZoom?: boolean
  showCompass?: boolean
  visualizePitch?: boolean
  resetDuration?: number
  compassTitle?: string
}

export interface GeocoderControlProps extends ControlProps {
  provider?: unknown
  placeholder?: string
  limit?: number
  debounce?: number
  minLength?: number
  collapsed?: boolean
  flyTo?: boolean
  zoom?: number
  marker?: boolean
  proximity?: boolean
  language?: string
  countries?: string[]
}

export interface FullscreenControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  container?: HTMLElement
  title?: string
  titleCancel?: string
}

export interface LocateControlProps extends ControlProps {
  /** The language of its titles. Default the map's `locale`, else the browser's. */
  locale?: string
  zoom?: number | null
  follow?: boolean
  showMarker?: boolean
  enableHighAccuracy?: boolean
  timeout?: number
  maximumAge?: number
}

export interface ScaleControlProps extends ControlProps {
  metric?: boolean
  imperial?: boolean
  maxWidth?: number
}

export interface AttributionControlProps extends ControlProps {
  prefix?: string | false
}

export const ZoomControl: (props: ZoomControlProps) => JSX.Element = createControlComponent<ZoomControlProps>(control.zoom as ControlFactory)
export const NavigationControl: (props: NavigationControlProps) => JSX.Element = createControlComponent<NavigationControlProps>(control.navigation as ControlFactory)
export const GeocoderControl: (props: GeocoderControlProps) => JSX.Element = createControlComponent<GeocoderControlProps>(control.geocoder as ControlFactory)
export const FullscreenControl: (props: FullscreenControlProps) => JSX.Element = createControlComponent<FullscreenControlProps>(control.fullscreen as ControlFactory)
export const LocateControl: (props: LocateControlProps) => JSX.Element = createControlComponent<LocateControlProps>(control.locate as ControlFactory)
export const ScaleControl: (props: ScaleControlProps) => JSX.Element = createControlComponent<ScaleControlProps>(control.scale as ControlFactory)
export const AttributionControl: (props: AttributionControlProps) => JSX.Element = createControlComponent<AttributionControlProps>(control.attribution as ControlFactory)
