// packages/react/src/Map.tsx
import type { CSSProperties, ReactElement, ReactNode } from 'react'
import type { TsMap as TsMapInstance } from 'ts-maps'
import type { MapEventProps } from './eventProps'
import { useEffect, useRef, useState } from 'react'
import { TsMap } from 'ts-maps'
import { EVENT_PROPS } from './eventProps'
import { MapContext } from './MapContext'

export interface MapProps extends MapEventProps {
  /** Map center as `[lat, lng]`. Followed when its value changes. */
  center?: [number, number]
  zoom?: number
  bearing?: number
  pitch?: number
  /** Style specification (object) or stylesheet URL. Followed when it changes. */
  style?: unknown
  /**
   * The language the built-in controls speak, unless one has its own
   * `locale`. Default the browser's. A change reaches each control the next
   * time it draws its words; give the control its own `locale` to relabel it
   * at once.
   */
  locale?: string
  /** CSS styles applied to the container div. */
  containerStyle?: CSSProperties
  /** CSS class applied to the container div. */
  className?: string
  /** Called once the underlying `TsMap` instance has mounted. */
  onLoad?: (map: TsMapInstance) => void
  children?: ReactNode
}

/** A style, by value: its URL, or its JSON. */
function styleKey(style: unknown): string {
  return typeof style === 'string' ? style : JSON.stringify(style)
}

/**
 * Root component that owns a `TsMap` instance and exposes it to descendants
 * via context. The instance is created on client-side mount only — during SSR
 * we render an empty container div.
 */
export function Map(props: MapProps): ReactElement {
  const {
    center,
    zoom,
    bearing,
    pitch,
    style,
    locale,
    containerStyle,
    className,
    onLoad,
    children,
    ...rest
  } = props

  const containerRef = useRef<HTMLDivElement | null>(null)
  const mapRef = useRef<TsMapInstance | null>(null)
  const [map, setMap] = useState<TsMapInstance | null>(null)
  // The latest event props, read when an event fires: listeners are bound
  // once per handler prop, not again for every render's new functions.
  const handlersRef = useRef<Record<string, unknown>>(rest)
  handlersRef.current = rest
  // The style the map was last given, by value: a style written inline is a
  // new object every render, and setting it again would fire style.load each
  // time.
  const appliedStyle = useRef<string | undefined>(undefined)

  useEffect(() => {
    if (!containerRef.current || mapRef.current)
      return

    const options: Record<string, unknown> = {}
    if (center !== undefined)
      options.center = center
    if (zoom !== undefined)
      options.zoom = zoom
    if (bearing !== undefined)
      options.bearing = bearing
    if (pitch !== undefined)
      options.pitch = pitch
    if (style !== undefined) {
      options.style = style
      appliedStyle.current = styleKey(style)
    }
    if (locale !== undefined)
      options.locale = locale

    const instance = new TsMap(containerRef.current, options)
    mapRef.current = instance
    setMap(instance)
    onLoad?.(instance)

    return () => {
      try {
        ;(instance as unknown as { remove?: () => void }).remove?.()
      }
      catch {
        // ignore cleanup errors; the host is being torn down
      }
      mapRef.current = null
      setMap(null)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Which event props are given: listeners change when one comes or goes,
  // and each calls whatever function the prop holds now.
  const bound = Object.keys(EVENT_PROPS).filter(prop => typeof (rest as Record<string, unknown>)[prop] === 'function').join(',')

  useEffect(() => {
    if (!map || !bound)
      return
    const bindings: { event: string, handler: (e: any) => void }[] = []
    for (const prop of bound.split(',')) {
      const event = EVENT_PROPS[prop]!
      const h = (e: any): void => {
        const handler = handlersRef.current[prop]
        if (typeof handler === 'function')
          handler(e)
      }
      map.on(event, h)
      bindings.push({ event, handler: h })
      // The map fires `load` from its constructor, before any listener
      // can exist: a map already loaded is told to this one now.
      if (event === 'load' && (map as any)._loaded)
        queueMicrotask(() => h({ type: 'load', target: map }))
    }
    return () => {
      for (const b of bindings)
        map.off(b.event, b.handler)
    }
  }, [map, bound])

  // Camera props are followed by value: a parent that re-renders with the
  // same `center` (a new array each time) mustn't undo a pan the user made.
  useEffect(() => {
    if (!map || center === undefined || zoom === undefined)
      return
    map.setView(center, zoom)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map, center?.[0], center?.[1], zoom])

  useEffect(() => {
    if (!map || style === undefined)
      return
    const key = styleKey(style)
    if (key === appliedStyle.current)
      return
    appliedStyle.current = key
    map.setStyle(style as Parameters<TsMapInstance['setStyle']>[0])
  }, [map, style])

  useEffect(() => {
    if (!map || bearing === undefined)
      return
    ;(map as unknown as { setBearing?: (b: number) => void }).setBearing?.(bearing)
  }, [map, bearing])

  useEffect(() => {
    if (!map || pitch === undefined)
      return
    ;(map as unknown as { setPitch?: (p: number) => void }).setPitch?.(pitch)
  }, [map, pitch])

  useEffect(() => {
    if (map)
      map.options.locale = locale
  }, [map, locale])

  return (
    <MapContext.Provider value={{ map }}>
      <div ref={containerRef} className={className} style={containerStyle}>
        {map ? children : null}
      </div>
    </MapContext.Provider>
  )
}

// packages/solid/src/Map.tsx
import type { JSX, ParentProps } from 'solid-js'
import type { TsMap as TsMapInstance } from 'ts-maps'
import type { MapEventProps } from './eventProps'
import type { Applied } from './follow'
import { createEffect, createSignal, on, onCleanup, onMount } from 'solid-js'
import { TsMap } from 'ts-maps'
import { MapContext } from './context'
import { syncEvents, unbindEvents } from './eventProps'
import { followBearing, followCamera, followPitch, followStyle } from './follow'

export interface MapProps extends MapEventProps {
  /** Map center as `[lat, lng]`. Followed: a new value moves the map. */
  center?: [number, number]
  zoom?: number
  bearing?: number
  pitch?: number
  /**
   * The map's style: a style object, such as `styles.light({ url })`, or a
   * stylesheet URL. A new one is set with `setStyle`.
   */
  style?: object | string
  /**
   * The language the built-in controls speak, unless one has its own
   * `locale`. Default the browser's. A change reaches each control the next
   * time it draws its words; give the control its own `locale` to relabel it
   * at once.
   */
  locale?: string
  /** CSS for the container div. */
  containerStyle?: JSX.CSSProperties | string
  /** A class for the container div. */
  class?: string
  /** Called with the `TsMap` once it is built. The map's `load` event is `onLoadEvent`. */
  // eslint-disable-next-line no-unused-vars
  onLoad?: (map: TsMapInstance) => void
}

type Handlers = Record<string, ((e: any) => void) | undefined>

export function Map(props: ParentProps<MapProps>): JSX.Element {
  const [map, setMap] = createSignal<TsMapInstance | null>(null)
  let container: HTMLDivElement | undefined

  // What the map was last given; see follow.ts.
  const applied: Applied = {}
  const bound: Record<string, (e: any) => void> = {}
  const loadState = { loadTold: false }
  // The props are the handlers: `props.onClick` is read when a click comes.
  const handlers = (): Handlers => props as unknown as Handlers

  // Children go in a wrapper of their own rather than straight into the map
  // container. Solid's `insert` treats a parent whose content it manages as
  // its to clear, and the map fills that container with panes the moment it is
  // created — so putting the children slot directly inside meant every pane
  // was wiped the instant `map()` flipped from null. `display: contents`
  // keeps the wrapper out of the layout entirely.
  //
  // A callback ref rather than `ref={container}`. The bare-variable form
  // depends on Solid's compiler recognising the variable and rewriting the
  // assignment, which it does not do under every configuration — and when it
  // does not, the ref is silently never set and the map never mounts. Written
  // this way it works the same however the JSX was compiled.
  const setContainer = (el: HTMLDivElement): void => {
    container = el
  }

  onMount(() => {
    if (!container)
      return
    const options: Record<string, unknown> = {}
    if (props.center !== undefined) options.center = props.center
    if (props.zoom !== undefined) options.zoom = props.zoom
    if (props.bearing !== undefined) options.bearing = props.bearing
    if (props.pitch !== undefined) options.pitch = props.pitch
    if (props.style !== undefined) options.style = props.style
    if (props.locale !== undefined) options.locale = props.locale
    Object.assign(applied, {
      center: options.center,
      zoom: options.zoom,
      bearing: options.bearing,
      pitch: options.pitch,
    })
    const instance = new TsMap(container, options)
    // Bound before anything else can run: a style given to the constructor
    // fires `style.load` a microtask later.
    syncEvents(instance, handlers(), handlers, bound, loadState)
    setMap(instance)
    props.onLoad?.(instance)
  })

  // Re-read when a handler prop changes: one is added or taken away.
  createEffect(() => {
    const instance = map()
    if (instance)
      syncEvents(instance, handlers(), handlers, bound, loadState)
  })

  createEffect(() => {
    const instance = map()
    const center = props.center
    const zoom = props.zoom
    if (instance)
      followCamera(instance, center, zoom, applied)
  })

  createEffect(() => {
    const instance = map()
    const bearing = props.bearing
    if (instance)
      followBearing(instance, bearing, applied)
  })

  createEffect(() => {
    const instance = map()
    const pitch = props.pitch
    if (instance)
      followPitch(instance, pitch, applied)
  })

  // Only when the prop changes, not on the first run: written inline,
  // `style={styles.light(...)}` makes a new object each time it is read, and
  // the constructor has already had the first one.
  createEffect(on(() => props.style, (style) => {
    const instance = map()
    if (instance)
      followStyle(instance, style, applied)
  }, { defer: true }))

  createEffect(() => {
    const instance = map()
    const locale = props.locale
    if (instance)
      instance.options.locale = locale
  })

  onCleanup(() => {
    const instance = map()
    if (instance)
      unbindEvents(instance, bound)
    try {
      ;(instance as unknown as { remove?: () => void } | null)?.remove?.()
    }
    catch {
      // ignore — host is being torn down
    }
    setMap(null)
  })

  return (
    <MapContext.Provider value={map}>
      <div ref={setContainer} class={props.class} style={props.containerStyle}>
        <div style={{ display: 'contents' }}>
          {map() ? props.children : null}
        </div>
      </div>
    </MapContext.Provider>
  )
}
