// packages/svelte/src/Source.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte'
  import { useMap } from './useMap'

  export let id: string
  export let type: 'vector' | 'raster' | 'raster-dem' | 'geojson'
  export let tiles: string[] | undefined = undefined
  export let tileSize: number | undefined = undefined
  export let data: unknown = undefined

  let added = false

  onMount(() => {
    const map = useMap() as unknown as {
      addSource?: (id: string, source: Record<string, unknown>) => void
      removeSource?: (id: string) => void
    } | null
    if (!map?.addSource) return
    const source: Record<string, unknown> = { type }
    if (tiles) source.tiles = tiles
    if (tileSize !== undefined) source.tileSize = tileSize
    if (data !== undefined) source.data = data
    map.addSource(id, source)
    added = true
  })

  onDestroy(() => {
    if (!added) return
    const map = useMap() as unknown as { removeSource?: (id: string) => void } | null
    map?.removeSource?.(id)
  })
</script>

// packages/solid/src/Source.tsx
import type { JSX } from 'solid-js'
import { onCleanup, onMount } from 'solid-js'
import { useMap } from './context'

export interface SourceProps {
  id: string
  type: 'vector' | 'raster' | 'raster-dem' | 'geojson'
  tiles?: string[]
  tileSize?: number
  data?: unknown
}

export function Source(props: SourceProps): JSX.Element {
  onMount(() => {
    const map = useMap() as unknown as {
      addSource?: (id: string, source: Record<string, unknown>) => void
    } | null
    if (!map?.addSource)
      return
    const source: Record<string, unknown> = { type: props.type }
    if (props.tiles) source.tiles = props.tiles
    if (props.tileSize !== undefined) source.tileSize = props.tileSize
    if (props.data !== undefined) source.data = props.data
    map.addSource(props.id, source)
  })

  onCleanup(() => {
    const map = useMap() as unknown as { removeSource?: (id: string) => void } | null
    map?.removeSource?.(props.id)
  })

  return null
}
