// packages/svelte/src/TurnByTurn.svelte
<script lang="ts">
  /**
   * Turn-by-turn navigation, after Apple Maps.
   *
   * ```svelte
   * <Map center={[37.79, -122.39]} zoom={13}>
   *   <TurnByTurn from={[37.7955, -122.3937]} to={[37.8029, -122.4484]} active={driving} onArrive={done} />
   * </Map>
   * ```
   *
   * Setting `from` and `to` previews the routes; `active` starts guidance.
   * Every prop is followed as it changes. Events are callback props with the
   * same names the other bindings use — `onPreview`, `onProgress`,
   * `onArrive`, …
   */
  import type { LatLngInput, TurnByTurnOptions } from 'ts-maps'
  import { onDestroy, onMount } from 'svelte'
  import { TURN_BY_TURN_EVENTS, TurnByTurn as TsTurnByTurn } from 'ts-maps'
  import { useMap } from './useMap'

  export let from: LatLngInput | null | undefined = undefined
  export let to: LatLngInput | null | undefined = undefined
  export let active = false
  export let profile: TurnByTurnOptions['profile'] = undefined
  export let units: TurnByTurnOptions['units'] = undefined
  export let voice: boolean | undefined = undefined
  export let simulate: TurnByTurnOptions['simulate'] = undefined
  export let alternatives: boolean | undefined = undefined
  export let destinationName: string | undefined = undefined
  export let directions: TurnByTurnOptions['directions'] = undefined
  /** The language of its cards and voice. Default the map's `locale`, else the browser's. */
  export let locale: string | undefined = undefined

  /* eslint-disable no-unused-vars */
  export let onReady: ((nav: TsTurnByTurn) => void) | undefined = undefined
  export let onPreview: ((e: any) => void) | undefined = undefined
  export let onRouteSelect: ((e: any) => void) | undefined = undefined
  export let onStart: ((e: any) => void) | undefined = undefined
  export let onProgress: ((e: any) => void) | undefined = undefined
  export let onInstruction: ((e: any) => void) | undefined = undefined
  export let onReroute: ((e: any) => void) | undefined = undefined
  export let onArrive: ((e: any) => void) | undefined = undefined
  export let onEnd: ((e: any) => void) | undefined = undefined
  export let onError: ((e: any) => void) | undefined = undefined
  /* eslint-enable no-unused-vars */

  let nav: TsTurnByTurn | null = null

  // Read at the moment of the event, so a changed handler is honoured.
  const handler = (prop: string): ((e: any) => void) | undefined => ({
    onPreview, onRouteSelect, onStart, onProgress, onInstruction, onReroute, onArrive, onEnd, onError,
  } as Record<string, ((e: any) => void) | undefined>)[prop]

  onMount(() => {
    const map = useMap()
    if (!map) return
    nav = new TsTurnByTurn(map, { profile, units, voice, simulate, alternatives, destinationName, directions, locale })
    for (const [event, prop] of Object.entries(TURN_BY_TURN_EVENTS))
      nav.on(event, (e: any) => handler(prop)?.(e))
    onReady?.(nav)
  })

  // Every option is followed: another `profile` or `directions` fetches a
  // showing preview again, `units` redraw the cards in place.
  $: if (nav) nav.sync({ from, to, active, profile, units, voice, simulate, alternatives, destinationName, directions, locale })

  onDestroy(() => {
    nav?.stop()
    nav = null
  })
</script>

// packages/solid/src/TurnByTurn.tsx
import type { JSX } from 'solid-js'
import type { LatLngInput, TurnByTurnOptions } from 'ts-maps'
import { createEffect, onCleanup } from 'solid-js'
import { TURN_BY_TURN_EVENTS, TurnByTurn as TsTurnByTurn } from 'ts-maps'
import { useMap } from './context'

/* eslint-disable no-unused-vars */
export interface TurnByTurnProps {
  /** Where the trip starts, `[lat, lng]` or `{ lat, lng }`. */
  from?: LatLngInput | null
  /** Where it ends. With both set, the routes between them are previewed. */
  to?: LatLngInput | null
  /** Guide along the chosen route. Off returns to the preview. */
  active?: boolean
  profile?: TurnByTurnOptions['profile']
  units?: TurnByTurnOptions['units']
  voice?: boolean
  simulate?: TurnByTurnOptions['simulate']
  alternatives?: boolean
  destinationName?: string
  directions?: TurnByTurnOptions['directions']
  /** The language of its cards and voice. Default the map's `locale`, else the browser's. */
  locale?: string
  /** The underlying `TurnByTurn`, for `selectRoute`, `recenter` and `update`. */
  onReady?: (nav: TsTurnByTurn) => void
  onPreview?: (e: any) => void
  onRouteSelect?: (e: any) => void
  onStart?: (e: any) => void
  onProgress?: (e: any) => void
  onInstruction?: (e: any) => void
  onReroute?: (e: any) => void
  onArrive?: (e: any) => void
  onEnd?: (e: any) => void
  onError?: (e: any) => void
}
/* eslint-enable no-unused-vars */

/**
 * Turn-by-turn navigation, after Apple Maps.
 *
 * ```tsx
 * <Map center={[37.79, -122.39]} zoom={13}>
 *   <TurnByTurn from={[37.7955, -122.3937]} to={[37.8029, -122.4484]} active={driving()} />
 * </Map>
 * ```
 *
 * Setting `from` and `to` previews the routes; `active` starts guidance.
 * Every prop is followed as it changes.
 */
export function TurnByTurn(props: TurnByTurnProps): JSX.Element {
  let nav: TsTurnByTurn | null = null

  // One effect for both: the map arrives through a signal, and every prop is
  // read here too, so a change to either brings the navigation into line —
  // whichever comes first. Another `profile` or `directions` fetches a
  // showing preview again; places are compared by value, so an unchanged
  // trip is not fetched again when another prop changes.
  createEffect(() => {
    const map = useMap()
    const target = {
      from: props.from,
      to: props.to,
      active: props.active,
      profile: props.profile,
      units: props.units,
      voice: props.voice,
      simulate: props.simulate,
      alternatives: props.alternatives,
      destinationName: props.destinationName,
      directions: props.directions,
      locale: props.locale,
    }
    if (!map)
      return
    if (!nav) {
      nav = new TsTurnByTurn(map, {
        profile: target.profile,
        units: target.units,
        voice: target.voice,
        simulate: target.simulate,
        alternatives: target.alternatives,
        destinationName: target.destinationName,
        directions: target.directions,
        locale: target.locale,
      })
      for (const [event, prop] of Object.entries(TURN_BY_TURN_EVENTS))
        nav.on(event, (e: any) => (props as any)[prop]?.(e))
      props.onReady?.(nav)
    }
    nav.sync(target)
  })

  onCleanup(() => {
    nav?.stop()
    nav = null
  })

  return null as unknown as JSX.Element
}
